name: Build APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v6

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Instalar dependências
        run: npm install

      - name: Criar projeto Android com Capacitor
        run: npx cap add android

      - name: Sincronizar app web
        run: npx cap sync android

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Configurar Android SDK
        uses: android-actions/setup-android@v3

      - name: Instalar SDK Android
        run: sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"

      - name: Gerar APK de teste
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Publicar APK como artefato
        uses: actions/upload-artifact@v4
        with:
          name: eletricista-pro-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30
